language: c
services: docker
os: linux
env:
    - PACKAGE=python TARGET=linux64 MODE=Debug
    - PACKAGE=dune-freetype TARGET=linux64 MODE=Debug
    - PACKAGE=haxx-libcurl TARGET=linux64 MODE=Debug
    - PACKAGE=fmod TARGET=linux64 MODE=Debug
    - PACKAGE=intel-tbb TARGET=linux64 MODE=Debug
    - PACKAGE=cryptopp TARGET=linux64 MODE=Debug
    - PACKAGE=ois TARGET=linux64 MODE=Debug
    - PACKAGE=bullet2 TARGET=linux64 MODE=Debug
script:
    - PACKAGE=$PACKAGE make $TARGET

