version: '3'
services:
    servfactor:
        build: .
        volumes:
            - .:/var/www/html/cpp
            - ./packages:/var/www/html/packages
        ports:
            - "8080:80"
        restart: always

