FROM nimmis/apache-php5

MAINTAINER Ricardo Marmolejo García <makiolo@gmail.com>

RUN echo "upload_max_filesize=800M" >> /etc/php5/apache2/php.ini
RUN echo "post_max_size=800M" >> /etc/php5/apache2/php.ini
RUN echo "max_input_time=300" >> /etc/php5/apache2/php.ini
RUN echo "max_execution_time=300" >> /etc/php5/apache2/php.ini

